### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by nicknikolov** [charlieroberts/gibber.server#1]
I'm running OS X 10.10.5
node -v
v0.12.0

```
in gibber. npm install gibber.server
npm WARN package.json jquery-commonjs@1.7.3 No README data

> ws@0.4.32 install /Users/nicknikolov/work/gibber/node_modules/gibber.server/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished

> hiredis@0.2.0 install /Users/nicknikolov/work/gibber/node_modules/gibber.server/node_modules/livedb/node_modules/hiredis
> node-gyp rebuild

  CC(target) Release/obj.target/hiredis/deps/hiredis/hiredis.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/net.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/async.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/read.o
  LIBTOOL-STATIC Release/hiredis.a
  CXX(target) Release/obj.target/hiredis/src/hiredis.o
  CXX(target) Release/obj.target/hiredis/src/reader.o
  SOLINK_MODULE(target) Release/hiredis.node
  SOLINK_MODULE(target) Release/hiredis.node: Finished

> streamws@0.1.1 install /Users/nicknikolov/work/gibber/node_modules/gibber.server/node_modules/node-core-audio/node_modules/audio-streamer/node_modules/binaryjs/node_modules/streamws
> node install.js

[ws v0.1.1] Attempting to compile blazing fast native extensions.
[ws v0.1.1] Native code compile failed (but the module will still work):
[ws v0.1.1] The native extensions are faster, but not required.
[ws v0.1.1] On Windows, native extensions require Visual Studio and Python.
[ws v0.1.1] On Unix, native extensions require Python, make and a C++ compiler.
[ws v0.1.1] Start npm with --ws:verbose to show compilation output (if any).

> node-core-audio@0.4.1 install /Users/nicknikolov/work/gibber/node_modules/gibber.server/node_modules/node-core-audio
> node-gyp rebuild

  CXX(target) Release/obj.target/NodeCoreAudio/NodeCoreAudio/AudioEngine.o
In file included from ../NodeCoreAudio/AudioEngine.cpp:9:
/Users/nicknikolov/work/gibber/node_modules/gibber.server/node_modules/node-core-audio/NodeCoreAudio/AudioEngine.h:32:50: error:
      no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
                static v8::Handle<v8::Value> NewInstance(const v8::Arguments& args);
                                                               ^~~~~~~~~~~~~
                                                               v8::internal::Arguments
/Users/nicknikolov/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../NodeCoreAudio/AudioEngine.cpp:9:
/Users/nicknikolov/work/gibber/node_modules/gibber.server/node_modules/node-core-audio/NodeCoreAudio/AudioEngine.h:44:43: error:
      no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
                static v8::Handle<v8::Value> New( const v8::Arguments& args );  //!< Create a v8 object
                                                        ^~~~~~~~~~~~~
                                                        v8::internal::Arguments
/Users/nicknikolov/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../NodeCoreAudio/AudioEngine.cpp:9:
/Users/nicknikolov/work/gibber/node_modules/gibber.server/node_modules/node-core-audio/NodeCoreAudio/AudioEngine.h:47:48: error:
      no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
                static v8::Handle<v8::Value> isActive( const v8::Arguments& args );
                                                             ^~~~~~~~~~~~~
                                                             v8::internal::Arguments
/Users/nicknikolov/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../NodeCoreAudio/AudioEngine.cpp:9:
/Users/nicknikolov/work/gibber/node_modules/gibber.server/node_modules/node-core-audio/NodeCoreAudio/AudioEngine.h:49:53: error:
      no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
                static v8::Handle<v8::Value> getDeviceName( const v8::Arguments& args );
                                                                  ^~~~~~~~~~~~~
                                                                  v8::internal::Arguments
/Users/nicknikolov/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../NodeCoreAudio/AudioEngine.cpp:9:
/Users/nicknikolov/work/gibber/node_modules/gibber.server/node_modules/node-core-audio/NodeCoreAudio/AudioEngine.h:51:53: error:
      no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
                static v8::Handle<v8::Value> getNumDevices( const v8::Arguments& args );
                                                                  ^~~~~~~~~~~~~
                                                                  v8::internal::Arguments
/Users/nicknikolov/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../NodeCoreAudio/AudioEngine.cpp:9:
/Users/nicknikolov/work/gibber/node_modules/gibber.server/node_modules/node-core-audio/NodeCoreAudio/AudioEngine.h:56:45: error:
      no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
                static v8::Handle<v8::Value> write( const v8::Arguments& args );                //!< Write sam...
                                                          ^~~~~~~~~~~~~
                                                          v8::internal::Arguments
/Users/nicknikolov/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../NodeCoreAudio/AudioEngine.cpp:9:
/Users/nicknikolov/work/gibber/node_modules/gibber.server/node_modules/node-core-audio/NodeCoreAudio/AudioEngine.h:57:44: error:
      no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
                static v8::Handle<v8::Value> read( const v8::Arguments& args );                 //!< Read samp...
                                                         ^~~~~~~~~~~~~
                                                         v8::internal::Arguments
/Users/nicknikolov/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../NodeCoreAudio/AudioEngine.cpp:9:
/Users/nicknikolov/work/gibber/node_modules/gibber.server/node_modules/node-core-audio/NodeCoreAudio/AudioEngine.h:58:53: error:
      no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
                static v8::Handle<v8::Value> isBufferEmpty( const v8::Arguments& args );        //!< Returns w...
                                                                  ^~~~~~~~~~~~~
                                                                  v8::internal::Arguments
/Users/nicknikolov/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../NodeCoreAudio/AudioEngine.cpp:9:
/Users/nicknikolov/work/gibber/node_modules/gibber.server/node_modules/node-core-audio/NodeCoreAudio/AudioEngine.h:60:50: error:
      no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
                static v8::Handle<v8::Value> setOptions( const v8::Arguments& args );   //!< Set options, rest...
                                                               ^~~~~~~~~~~~~
                                                               v8::internal::Arguments
/Users/nicknikolov/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../NodeCoreAudio/AudioEngine.cpp:9:
/Users/nicknikolov/work/gibber/node_modules/gibber.server/node_modules/node-core-audio/NodeCoreAudio/AudioEngine.h:61:50: error:
      no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
                static v8::Handle<v8::Value> getOptions( const v8::Arguments& args );   //!< Gets options
                                                               ^~~~~~~~~~~~~
                                                               v8::internal::Arguments
/Users/nicknikolov/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../NodeCoreAudio/AudioEngine.cpp:30:2: warning: field 'm_pLocker' will be initialized after field 'm_bOutputIsEmpty'
      [-Wreorder]
        m_pLocker(new Locker(Isolate::GetCurrent())),
        ^
../NodeCoreAudio/AudioEngine.cpp:59:31: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of
      type 'int'
        m_hInputBuffer = Array::New( m_uInputChannels );
                                     ^~~~~~~~~~~~~~~~
/Users/nicknikolov/.node-gyp/0.12.0/deps/v8/include/v8.h:2417:36: note: passing argument to parameter 'isolate' here
  static Local<Array> New(Isolate* isolate, int length = 0);
                                   ^
../NodeCoreAudio/AudioEngine.cpp:61:45: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of
      type 'int'
                m_hInputBuffer->Set( iChannel, Array::New(m_uSamplesPerBuffer) );
                                                          ^~~~~~~~~~~~~~~~~~~
/Users/nicknikolov/.node-gyp/0.12.0/deps/v8/include/v8.h:2417:36: note: passing argument to parameter 'isolate' here
  static Local<Array> New(Isolate* isolate, int length = 0);
                                   ^
../NodeCoreAudio/AudioEngine.cpp:68:48: error: no member named 'New' in 'v8::String'
                ThrowException( Exception::TypeError(String::New("Error: No default input device")) );
                                                     ~~~~~~~~^
../NodeCoreAudio/AudioEngine.cpp:73:48: error: no member named 'New' in 'v8::String'
                ThrowException( Exception::TypeError(String::New("Error: No default output device")) );
                                                     ~~~~~~~~^
../NodeCoreAudio/AudioEngine.cpp:77:48: error: no member named 'New' in 'v8::String'
                ThrowException( Exception::TypeError(String::New("Failed to initialize audio engine")) );
                                                     ~~~~~~~~^
../NodeCoreAudio/AudioEngine.cpp:102:48: error: no member named 'New' in 'v8::String'
                ThrowException( Exception::TypeError(String::New("Failed to open audio stream")) );
                                                     ~~~~~~~~^
../NodeCoreAudio/AudioEngine.cpp:108:48: error: no member named 'New' in 'v8::String'
                ThrowException( Exception::TypeError(String::New("Failed to start audio stream")) );
                                                     ~~~~~~~~^
../NodeCoreAudio/AudioEngine.cpp:118:60: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
v8::Handle<v8::Value> Audio::AudioEngine::getOptions(const v8::Arguments& args){
                                                           ^~~~~~~~~~~~~
                                                           v8::internal::Arguments
/Users/nicknikolov/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../NodeCoreAudio/AudioEngine.cpp:119:9: error: no matching constructor for initialization of 'v8::Locker'
        Locker v8Locker;
               ^
/Users/nicknikolov/.node-gyp/0.12.0/deps/v8/include/v8.h:5477:22: note: candidate constructor not viable: requires
      single argument 'isolate', but no arguments were provided
  V8_INLINE explicit Locker(Isolate* isolate) { Initialize(isolate); }
                     ^
/Users/nicknikolov/.node-gyp/0.12.0/deps/v8/include/v8.h:5502:3: note: candidate constructor not viable: requires 1
      argument, but 0 were provided
  Locker(const Locker&);
  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make: *** [Release/obj.target/NodeCoreAudio/NodeCoreAudio/AudioEngine.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/nicknikolov/work/gibber/node_modules/gibber.server/node_modules/node-core-audio
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "gibber.server"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.6
npm ERR! code ELIFECYCLE

npm ERR! node-core-audio@0.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-core-audio@0.4.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-core-audio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-core-audio
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nicknikolov/work/gibber/npm-debug.log
```

**Comment by charlieroberts** [comment]
OK, I've been thinking about changing back to using web-audio-api instead of node-core-audio... I'll push that change soon (in the next few days) and we'll see if it helps with your build issues. Leaving this open until then.

In the meantime, if you comment out line #12 of gibber_rtc.js and remove the requirement for node-core-audio from the package.json you should be able to build and run the server.

**Comment by Leetcore** [comment]
I did comment out line #12 but coreAudio is used on line #46. I comment that out too. I removed the line "node-core-audio" from package.json but it is still trying to install it. Same error.
